/* Exporting the ChalkAdvanced class from the src/chalk-advanced.js file. */
const {
  black,
  red,
  green,
  yellow,
  blue,
  magenta,
  cyan,
  white,
  gray,
  redBright,
  greenBright,
  yellowBright,
  blueBright,
  magentaBright,
  cyanBright,
  whiteBright,
  bgBlack,
  bgRed,
  bgGreen,
  bgYellow,
  bgBlue,
  bgMagenta,
  bgCyan,
  bgWhite,
  bgRedBright,
  bgGreenBright,
  bgYellowBright,
  bgBlueBright,
  bgMagentaBright,
  bgCyanBright,
  bgWhiteBright,
  bold,
  dim,
  italic,
  underline,
  inverse,
  hide,
  strikethrough,
} = require("./src/ChalkAdvanced");

const { hex } = require("./src/components/hex");
const { rgb } = require("./src/components/rgb");
const { hsl } = require("./src/components/hsl");

module.exports = {
  ChalkAdvanced: require("./src/ChalkAdvanced"),
  black: black,
  red: red,
  green: green,
  yellow: yellow,
  blue: blue,
  magenta: magenta,
  cyan: cyan,
  white: white,
  gray: gray,
  redBright: redBright,
  greenBright: greenBright,
  yellowBright: yellowBright,
  blueBright: blueBright,
  magentaBright: magentaBright,
  cyanBright: cyanBright,
  whiteBright: whiteBright,
  bgBlack: bgBlack,
  bgRed: bgRed,
  bgGreen: bgGreen,
  bgYellow: bgYellow,
  bgBlue: bgBlue,
  bgMagenta: bgMagenta,
  bgCyan: bgCyan,
  bgWhite: bgWhite,
  bgRedBright: bgRedBright,
  bgGreenBright: bgGreenBright,
  bgYellowBright: bgYellowBright,
  bgBlueBright: bgBlueBright,
  bgMagentaBright: bgMagentaBright,
  bgCyanBright: bgCyanBright,
  bgWhiteBright: bgWhiteBright,
  bold: bold,
  dim: dim,
  italic: italic,
  underline: underline,
  inverse: inverse,
  hide: hide,
  strikethrough: strikethrough,
  hex: hex,
  rgb: rgb,
  hsl: hsl,
};
